pipeline:
  eslint:
    image: node:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    comands:
      - npm install
      - npm run lint
    when:
      event: [pull_request]

branches: [ master, "*:master" ]